name: Java CI with Gradle

on:
  push:
    branches: [ llama ]
  pull_request:
    branches: [ llama ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: Optifabric-Artifact
          path: build/libs/optifabric-*.*.jar
          if-no-files-found: error
#      - name: Upload files to a GitHub release
#        uses: svenstaro/upload-release-action@2.2.1
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file_glob: true
#          file: build/libs/optifabric-*.*.jar
#          tag: ${{ github.ref }}
#          overwrite: true
#          body: "This is my release text"
      - name: Download  
        uses: actions/download-artifact@v2
